SELECT * FROM PRODUTOS WHERE CODIGO = '1040107';

UPDATE PRODUTOS SET PRECO_LISTA = 5.2 WHERE CODIGO = '1040107';

UPDATE PRODUTOS SET SABOR = 'Laranja', EMBALAGEM = 'PET' WHERE CODIGO = '1040107';

-- REPLACE ALTERA UM PEDAÇO DE UM TEXTO SUBS POR OUTRO TEXTO

SELECT DESCRITOR, REPLACE(DESCRITOR, 'Melancia', 'Laranja') FROM PRODUTOS WHERE CODIGO = '1040107';
UPDATE PRODUTOS SET DESCRITOR = REPLACE(DESCRITOR, 'Melancia', 'Laranja') WHERE CODIGO = '1040107';



