 INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
     VALUES ('1001001','Sabor dos Alpes 700 ml - Manga','Manga','700 ml','Garrafa',7.50);
	 
	   INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
     VALUES ('1001000','Sabor dos Alpes 700 ml - Mel�o','Mel�o','700 ml','Garrafa',7.50);
	 
	   INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
     VALUES ('1001002','Sabor dos Alpes 700 ml - Graviola','Graviola','700 ml','Garrafa',7.50);
	 
	  INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
     VALUES ('1001003','Sabor dos Alpes 700 ml - Tangerina','Tangerina','700 ml','Garrafa',7.50);
	 
	  INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
     VALUES ('1001004','Sabor dos Alpes 700 ml - Abacate','Abacate','700 ml','Garrafa',7.50);
	 
	  INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
     VALUES ('1001005','Sabor dos Alpes 700 ml - A�ai','A�ai','700 ml','Garrafa',7.50);
	 
	  INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
     VALUES ('1001006','Sabor dos Alpes 1 Litro - Manga','Manga','1 Litro','Garrafa',7.50);
	 
	  INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
     VALUES ('1001007','Sabor dos Alpes 1 Litro - Mel�o','Mel�o','1 Litro','Garrafa',7.50);
	 
	  INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
     VALUES ('1001008','Sabor dos Alpes 1 Litro - Graviola','Graviola','1 Litro','Garrafa',7.50);
	 
	  INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
     VALUES ('1001009','Sabor dos Alpes 1 Litro - Tangerina','Tangerina','1 Litro','Garrafa',7.50);
	 
	  INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
     VALUES ('1001010','Sabor dos Alpes 1 Litro - Abacate','Abacate','1 Litro','Garrafa',7.50);
	
 
	 SELECT * from PRODUTOS WHERE SUBSTR(DESCRITOR,1,15) = 'Sabor dos Alpes';
     
     SELECT COUNT(*) FROM PRODUTOS;
SELECT COUNT(*) FROM TABELA_DE_PRODUTOS_FONTE;

-- MOSTRA TODOS OS DADOS
SELECT
P.CODIGO AS CODIGO_PRODUTOS, TPF.CODIGO_DO_PRODUTO AS CODIGO_FONTE,
P.DESCRITOR AS DESCRITOR_PRODUTOS, TPF.NOME_DO_PRODUTO AS DESCRITOR_FONTE
FROM
PRODUTOS P
INNER JOIN
TABELA_DE_PRODUTOS_FONTE TPF
ON P.CODIGO = TPF.CODIGO_DO_PRODUTO;

--- MOSTRA VALORES QUE N EXISTE NA TABELA FONTE
SELECT
P.CODIGO AS CODIGO_PRODUTOS, TPF.CODIGO_DO_PRODUTO AS CODIGO_FONTE,
P.DESCRITOR AS DESCRITOR_PRODUTOS, TPF.NOME_DO_PRODUTO AS DESCRITOR_FONTE
FROM
PRODUTOS P LEFT JOIN TABELA_DE_PRODUTOS_FONTE TPF
ON P.CODIGO = TPF.CODIGO_DO_PRODUTO;

-- LISTAR 18 lINHAS, QUE EXISTE NA TABELA DE PRODUTOS, E N EXISTE NA TABELA DE PRODUTOS FONTE QUE É NOSSA PRINCIPAL
SELECT
P.CODIGO FROM PRODUTOS P LEFT JOIN TABELA_DE_PRODUTOS_FONTE TPF
ON P.CODIGO = TPF.CODIGO_DO_PRODUTO
WHERE TPF.CODIGO_DO_PRODUTO IS NULL;

--- LOGO ESSE COMANDO VAI EXCLUIR OS DADOS DE CIMA 
DELETE FROM PRODUTOS P WHERE 
P.CODIGO IN  (
SELECT P.CODIGO FROM PRODUTOS P LEFT JOIN TABELA_DE_PRODUTOS_FONTE TPF
ON P.CODIGO = TPF.CODIGO_DO_PRODUTO
WHERE TPF.CODIGO_DO_PRODUTO IS NULL
);