ALTER TABLE ITENS_NOTAS
ADD CONSTRAINT FK_NOTAS
FOREIGN KEY (NUMERO)
REFERENCES NOTAS (NUMERO);

-- Adiciona a chave estrangeira na tabela ITENS_NOTAS referenciando PRODUTOS
ALTER TABLE ITENS_NOTAS
ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO)
REFERENCES PRODUTOS (CODIGO);

-- Adiciona a chave estrangeira na tabela TABELA_DE_VENDAS referenciando VENDEDORES
ALTER TABLE NOTAS
ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA)
REFERENCES VENDEDORES (MATRICULA);

-- Adiciona a chave estrangeira na tabela TABELA_DE_VENDAS referenciando CLIENTES

ALTER TABLE NOTAS
ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY (CPF)
REFERENCES CLIENTES (CPF);



-- REMOVENDO CHAVES ESTREGEIRAS
ALTER TABLE NOTAS
DROP CONSTRAINT FK_VENDEDORES; -- Se já existir

ALTER TABLE ITENS_NOTAS
DROP CONSTRAINT FK_CLIENTES; -- Se já existir

ALTER TABLE NOTAS
DROP CONSTRAINT FK_CLIENTES; -- Se já existir

ALTER TABLE ITENS_NOTAS
DROP CONSTRAINT FK_NOTAS; -- Se já existir

ALTER TABLE ITENS_NOTAS
DROP CONSTRAINT FK_PRODUTOS; -- Se já existir