create table PRODUTOS2 as (select * from produtos);

SELECT * FROM PRODUTOS2;

UPDATE PRODUTOS2 SET PRECO_LISTA = 8;

COMMIT;

UPDATE PRODUTOS2 SET PRECO_LISTA = 7;

ROLLBACK; -- ELE VOLTA SO ESTADO ANTERIOR AO ESTADO DO ULTIMO COMMIT
