  CREATE TABLE "TABELA_DE_VENDEDORES_FONTE" 
   ("MATRICULA" NVARCHAR2(5), 
    "NOME" NVARCHAR2(100), 
    "PERCENTUAL_COMISSAO" FLOAT(126), 
    "DATA_ADMISSAO" DATE, 
    "DE_FERIAS" NUMBER(1,0), 
    "BAIRRO" NVARCHAR2(50)
   );

Insert into TABELA_DE_VENDEDORES_FONTE (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS,BAIRRO) values ('00235','Marcio Almeida Silva','0,08',to_date('15/08/14','DD/MM/RR'),'0','Tijuca');
Insert into TABELA_DE_VENDEDORES_FONTE (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS,BAIRRO) values ('00236','Claudia Morais','0,08',to_date('17/09/13','DD/MM/RR'),'1','Jardins');
Insert into TABELA_DE_VENDEDORES_FONTE (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS,BAIRRO) values ('00237','Roberta Martins','0,11',to_date('18/03/17','DD/MM/RR'),'1','Copacabana');
Insert into TABELA_DE_VENDEDORES_FONTE (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS,BAIRRO) values ('00238','Pericles Alves','0,11',to_date('21/08/16','DD/MM/RR'),'0','Santo Amaro');


SELECT * FROM VENDEDORES V;
SELECT * FROM TABELA_DE_VENDEDORES_FONTE TVF;

SELECT
V.MATRICULA AS MATRICULA_VENDEDORES, TVF.MATRICULA AS MATRICULA_FONTE, V.FERIAS AS FERIAS_VENDEDORES, TVF.DE_FERIAS AS FERIAS_FONTE
FROM
VENDEDORES V
INNER JOIN
TABELA_DE_VENDEDORES_FONTE TVF
ON V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3);

-- SIMULAÇÃO, DEU UMA ALTERAÇÃO NO SISTEMA
UPDATE TABELA_DE_VENDEDORES_FONTE SET DE_FERIAS = 0 WHERE MATRICULA IN ('00236','00237');
UPDATE TABELA_DE_VENDEDORES_FONTE SET DE_FERIAS = 1 WHERE MATRICULA IN ('00235','00238');

---
UPDATE VENDEDORES V SET V.FERIAS = 0 WHERE V.MATRICULA = '235';


--- n funcionou
UPDATE VENDEDORES V INNER JOIN TABELA_DE_VENDEDORES_FONTE TVF ON V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3)
SET V.FERIAS = TVF.DE_FERIAS;