INSERT INTO TAB1 (ID, DESCRITOR, VALOR) VALUES ('2', 'CLIENTE 2', 10);


INSERT INTO TAB2 (LOG, DATA_CRIACAO) VALUES ('CLIENTE INCLUIDO', SYSDATE);


INSERT INTO TAB1 (ID, DESCRITOR, VALOR) VALUES ('3', 'CLIENTE 3', 20);

--- TRIGGER = AO INCLUIR NA TABELA TAB1 ESCREVA O LOG

DELETE FROM TAB WHERE ID=3;

---- TRIGGER = AO EXCLUIR NA TABELA TAB1 ESCREVA O LOG DE EXCLUSÃO

DELETE FROM ITENS_NOTAS;
DELETE FROM NOTAS;

SELECT * FROM CLIENTES;
-- CLIENTE: 1471156710

SELECT * FROM VENDEDORES;
-- VENDEDOR: 235

SELECT * FROM PRODUTOS;
-- PRODUTO: 100889

SELECT * FROM NOTAS;
INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('001', TO_DATE('2019-01-01','YYYY-MM-DD'), '1471156710', '235', 0.1);

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('002', TO_DATE('2019-01-01','YYYY-MM-DD'), '1471156710', '235', 0.1);

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('003', TO_DATE('2019-01-02','YYYY-MM-DD'), '1471156710', '235', 0.1);

SELECT * FROM ITENS_NOTAS;
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('001', '1040115', 10, 10);

INSERT INTO ITENS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('002', '1040115', 15, 10);

INSERT INTO ITENS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('003', '1040115', 18, 10);

SELECT * FROM ITENS_NOTAS;
SELECT * FROM NOTAS;

SELECT
N.DATA_VENDA, SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
FROM NOTAS N
INNER JOIN ITENS_NOTAS ITN
ON N.NUMERO = ITN.NUMERO
GROUP BY N.DATA_VENDA;

CREATE TABLE TAB_FATURAMENTO (DATA_VENDA DATE NULL, FATURAMENTO FLOAT);

DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT
N.DATA_VENDA, SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
FROM NOTAS N
INNER JOIN ITENS_NOTAS ITN
ON N.NUMERO = ITN.NUMERO
GROUP BY N.DATA_VENDA;

SELECT * FROM TAB_FATURAMENTO;

--- NOTAS NOVAS
INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('004', TO_DATE('2019-01-02','YYYY-MM-DD'), '1471156710', '235', 0.1);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('004', '1040115', 21, 10);


DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT
N.DATA_VENDA, SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
FROM NOTAS N
INNER JOIN ITENS_NOTAS ITN
ON N.NUMERO = ITN.NUMERO
GROUP BY N.DATA_VENDA;

SELECT * FROM TAB_FATURAMENTO;


----- No último vídeo, identificamos o problema: toda vez que incluirmos dados de nota fiscal e de item de nota fiscal, 
----  queremos recalcular automaticamente o valor das vendas por dia, gravando essa atualização
---- na tabela de faturamento. A "TAB_FATURAMENTO" é uma tabela agregada que possui os valores usados para um relatório emitido a todo momento para nosso cliente.

