SELECT * FROM TAB_FATURAMENTO;

SELECT * FROM NOTAS;


CREATE OR REPLACE TRIGGER TG_TAB_FATURAMENTO
AFTER INSERT OR UPDATE OR DELETE ON ITENS_NOTAS
BEGIN
DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT
N.DATA_VENDA, SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
FROM
NOTAS N
INNER JOIN
ITENS_NOTAS ITN
ON N.NUMERO = ITN.NUMERO
GROUP BY N.DATA_VENDA;
END;

-- VAI ATUALIZAR O TAB_FATURAMENTO
UPDATE ITENS_NOTAS SET QUANTIDADE = 66000 WHERE NUMERO = '007';
SELECT * FROM TAB_FATURAMENTO;


--- VAI EXCLUIR A NOTA
DELETE ITENS_NOTAS WHERE NUMERO  = '007';
DELETE NOTAS WHERE NUMERO  = '007';
SELECT * FROM TAB_FATURAMENTO;

--- COLOCA NOVAS NOTAS

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('005', TO_DATE('2019-01-04','YYYY-MM-DD'), '1471156710', '235', 0.1);

INSERT INTO ITENS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('005', '1040115',20, 11);
