SELECT V.MATRICULA AS MATRICULA_VENDEDORES, 
V.FERIAS AS FERIAS_VENDEDORES
FROM VENDEDORES V
WHERE EXISTS
(
SELECT 1 FROM TABELA_DE_VENDEDORES_FONTE TVF
WHERE V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3)
);


--- Aplicando o EXISTS no UPDATE
UPDATE VENDEDORES V SET V.FERIAS =
(SELECT TVF.DE_FERIAS FROM TABELA_DE_VENDEDORES_FONTE TVF
WHERE V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3))
WHERE EXISTS
(SELECT 1 FROM TABELA_DE_VENDEDORES_FONTE TVF
WHERE V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3));


--- VERIFICAR SE SINCRONIZOU 
SELECT V.MATRICULA AS MATRICULA_VENDEDORES, TVF.MATRICULA AS MASTRICULA_FONTE,
V.FERIAS AS FERIAS_VENDEDORES, TVF.DE_FERIAS AS FERIAS_FONTE
FROM VENDEDORES V INNER JOIN TABELA_DE_VENDEDORES_FONTE TVF ON V.MATRICULA =  SUBSTR(TVF.MATRICULA, 3, 3);