/*OBSERVAR EMBALAGENS E PRODUTOS*/
SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos;

/*CONTAGEM DE EMBALAGEM*/
select EMBALAGEM, count(*) AS CONTADOR 
FROM tabela_de_produtos
GROUP BY EMBALAGEM;

/*PRODUTOS COM MAIOR FATURAMENTO*/
SELECT EMBALAGEM, SUM(QUANTIDADE * PRECO) AS FATURAMENTO
FROM tabela_de_produtos A 
INNER JOIN itens_notas_fiscais B
ON A.CODIGO_DO_PRODUTO = B.CODIGO_DO_PRODUTO
GROUP BY EMBALAGEM;

SELECT * FROM preço_maximo;

/*PERCENTUAL*/
SELECT A.NOME_DO_PRODUTO, A.PRECO_DE_LISTA, X.PRECO_MAXIMO, 
((A.PRECO_DE_LISTA / X.PRECO_MAXIMO)-1)*100 AS Percentual 
from tabela_de_produtos A
INNER JOIN preço_maximo X
ON A.EMBALAGEM = X.EMBALAGEM
ORDER BY Percentual











