-- SUBCONSULTA -> Vamos observar os clientes que passaram do limite  
SELECT 
    X.CPF, 
    X.NOME, 
    X.MES_ANO, 
    X.QUANTIDADES_VENDAS, 
    X.QUANTIDADES_LIMITE, 
    X.QUANTIDADES_LIMITE - X.QUANTIDADES_VENDAS AS DIFERENÇA
FROM (
    SELECT 
        NF.CPF, 
        TC.NOME, 
        DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO, 
        SUM(INF.QUANTIDADE) AS QUANTIDADES_VENDAS, 
        MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADES_LIMITE
    FROM NOTAS_FISCAIS NF
    INNER JOIN ITENS_NOTAS_FISCAIS INF
        ON NF.NUMERO = INF.NUMERO
    INNER JOIN TABELA_DE_CLIENTES TC
        ON TC.CPF = NF.CPF
    GROUP BY NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m')
) X;

-- Criamos um status (INVÁLIDO e VÁLIDO)  
SELECT 
    X.CPF, 
    X.NOME, 
    X.MES_ANO, 
    X.QUANTIDADES_VENDAS, 
    X.QUANTIDADES_LIMITE,
    CASE 
        WHEN (X.QUANTIDADES_LIMITE - X.QUANTIDADES_VENDAS) < 0 THEN 'INVÁLIDO'
        ELSE 'VÁLIDO' 
    END AS STATUS_VENDA
FROM (
    SELECT 
        NF.CPF, 
        TC.NOME, 
        DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO, 
        SUM(INF.QUANTIDADE) AS QUANTIDADES_VENDAS, 
        MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADES_LIMITE
    FROM NOTAS_FISCAIS NF
    INNER JOIN ITENS_NOTAS_FISCAIS INF
        ON NF.NUMERO = INF.NUMERO
    INNER JOIN TABELA_DE_CLIENTES TC
        ON TC.CPF = NF.CPF
    GROUP BY NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m')
) X;











