
select * from [ITENS NOTAS FISCAIS] A
INNER JOIN [NOTAS FISCAIS] B 
ON A.NUMERO = B.NUMERO;

SELECT YEAR([DATA]), SUM([QUANTIDADE]*[PREÇO]) AS FATURAMENTO 
FROM [NOTAS FISCAIS] A
INNER JOIN [ITENS NOTAS FISCAIS] B
ON A.NUMERO = B.NUMERO
GROUP BY YEAR([DATA])